### ISSUE TITLE
Speech support Request

### ISSUE THREAD

**Issue by vdegenne** [everyonesdesign/Chess-Helper#26] opened 2020-11-03 23:00 UTC
Hey,

I see you plan to integrate speech support in the extension. Any news about this ? Are you still working on this ?
Maybe I could help and contribute if you tell me what is the latest issue you're facing on the implementation phase.

It shouldn't be that hard, all it needs is to create an event listener on the game board and use native JavaScript TTS to speak the moves.

**Comment by everyonesdesign** [comment] 2020-11-04 18:22
Hey!

Actually, it's already implemented (as in: chess.com announces the move that is made), but you need to uncomment this line: [link](https://github.com/everyonesdesign/Chess-Helper/blob/master/app/src/index.ts#L102)

The reason it's not shipped yet is that I wasn't able to come up with an approach to display the extension preferences that would satisfy me. Feel free to check this old WIP branch: [link](https://github.com/everyonesdesign/Chess-Helper/compare/preferences). It looks somewhat like this:

<img src="https://user-images.githubusercontent.com/3520704/98153030-e04c6300-1ed2-11eb-8721-d82748e9d274.png" width="248" />

But I don't know... this ellipsis button kind of breaks the simplicity of the original design, which is plain input field. I liked the simple approach there.

Maybe it's possible to create a command to toggle this function (similar to `/blindfold`)? I guess that would be OK.

Another aspect of voice-related stuff: at some point I also wanted to create a voice recognition for input of moves. See [this WIP branch](https://github.com/everyonesdesign/Chess-Helper/compare/speech-api).

Unfortunately, there's an old issue in Chromium that prevents from using grammars for voice recognition: [bug tracker link](https://bugs.chromium.org/p/chromium/issues/detail?id=680944#c18). As without grammar voice recognition would be pretty much useless in this case, I decided to wait with that at least until the issue is resolved.

**Comment by everyonesdesign** [comment] 2020-11-04 18:41
Added this simple MR: #27 

What do you think?

**Comment by vdegenne** [comment] 2020-11-04 20:59
@everyonesdesign Hey! Yes localStorage is best suited for that.
By the way I couldn't resist to look into the code and find the line to uncomment but then I was busy to tweak things around because the speechSynthesis was not working everywhere.

There are two cases where it doesn't work:

**1. "When I start a new live game"**. The reason is because the board gets renewed by Chess interface (you can see the board flashing as if it was deleted and then recreated for the new game to start). Because of that the "Move" listener is no longer used. We should find a way to rebind the listener to the new board.

**2. "The listener is bind but the `onMove` method of `VueChessboard` class is deprecated"**. We should replace

```javascript
this.store._events['chessboard-makeMove'].push((event) => {
...
```

with

```javascript
this.store.chessboard.on('MOVE_PIECES', (event) => {
...
```

Right ? And then also modify the content of this function to pass a valid `IMoveDetails` object to the `fn` callback.
(I noticed that the `game` object has `getLastMove` method which could be used to easily extract information on the move listener.)

Can you confirm you have the same behaviors 1 and 2 ?

By the way the reason I was having a canvas in some part of the website is because I was using "arcade" animations from the options.... But I think we have  the same version of the website, what system and browser are you using ?

**Comment by vdegenne** [comment] 2020-11-04 21:13
As for the setting disposition yes I think the command approach is the best, maybe something like `/speech` and use the toaster to display `speech: on` or `speech: off`

**Comment by everyonesdesign** [comment] 2020-11-05 18:13
> When I start a new live game

Hey, are you talking about "live" menu item or about "play (BETA)" menuitem?

![image](https://user-images.githubusercontent.com/3520704/98279632-7d260380-1f9a-11eb-8edb-1790b7d068d6.png)

It seems that "live" is still using Vue, but "play BETA" relies on component board.

> "The listener is bind but the onMove method of VueChessboard class is deprecated".

Where do you see that? in console? I tried "MOVE_PIECES" and it didn't work for me, unfortunately. I'm not able to find the proper event for Vue.js board at the moment (I need it to be called for moves made by both sides, except premoves. Premoves need to be announced when they're commited as a move).

> As for the setting disposition yes I think the command approach is the best, maybe something like /speech and use the toaster to display speech: on or speech: off.

Yeah, this is already done in #28 (I added`/speech` command).

**Comment by everyonesdesign** [comment] 2020-11-05 18:15
> By the way the reason I was having a canvas in some part of the website is because I was using "arcade" animations from the options.... But I think we have the same version of the website, what system and browser are you using ?

Interesting, maybe it makes sense to create an e2e test for this mode. How do you enable it?

**Comment by vdegenne** [comment] 2020-11-05 22:45
`Hey, are you talking about "live" menu item or about "play (BETA)" menuitem?`

Sorry for the confusion, I was talking about "play (BETA)" which is a Component board and you already fixed it with `_watchBoardChange` so I guess it's fine because we can also watch "live games" (by "live" here I mean other people playing).

But in the "Live Chess" section of the website the board is a Vue (both while playing or watching other people play). I guess it's fine because that part of the website is going to be replaced by the "play (BETA)" right ?
But if you really want to also fix `VueChessboard` please check #29.

**Comment by vdegenne** [comment] 2020-11-05 22:50
Also this is how I change the animation to arcade : 

![arcade animation](https://user-images.githubusercontent.com/2827383/98305116-89718700-1fc1-11eb-9892-b1c88eb1afa0.png)

**Comment by everyonesdesign** [comment] 2020-11-08 08:26
> But in the "Live Chess" section of the website the board is a Vue (both while playing or watching other people play). I guess it's fine because that part of the website is going to be replaced by the "play (BETA)" right ?

I think that they're going to change the chessboard to component one everywhere, yes. However, I would hold shipping new features that work only in some types of boards (since for user it might be not obvious when the feature will be working and when it will not).

> please check #29.

Checked. There's no data in the events, so I sourced it from history tree, see 37cc959ad4345816fd99c9fd58e1d29f0961edba . 

However, the events handling you suggest (`this.store.chessboard.on('MOVE_PIECES'`) seems to be triggered in many cases, e.g. when you're clicking on a certain move in game history; the events are triggered on board init (causing announcing the previous game's last move three times), checkmate seems to be annouced twice etc. and I don't see enough context in the event to distinguish between an actual move and false triggers.

Do you have ideas on how to work around this issue?

**Comment by everyonesdesign** [comment] 2021-02-16 21:44
Closing the issue as it seems that we won't be able to ship it at least until Chess.com discontinues Vue.js board

Also see 7aa2dd9f6b4b07db6c9533a7356a9d6c38f3327d for more details

This decision might be reverted in the future

**Closed by everyonesdesign** 2021-02-16 21:44 UTC
